server:
  port: 8085
  servlet:
   context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 110204
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  signerKey: "g43AodlsxhYbbHjL7TWzmYmpK6q391q5rCpUgWklkveqMvZVO9+YE6FaJRQlQR34"
